[package]
name = "myip"
license = "MIT"
version.workspace = true
edition.workspace = true

[dependencies]
spin-executor = "3.0.1"
spin-sdk = "3.0.1"
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:myip"
