[package]
name = "myip"
license = "MIT"
version.workspace = true
edition.workspace = true

[package.metadata.component]
package = "component:myip"

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
spin-executor.workspace = true
wit-bindgen-rt.workspace = true
