[package]
name = "filesystem"
license.workspace = true
version.workspace = true
edition.workspace = true

[package.metadata.component]
package = "component:filesystem"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
wit-bindgen-rt.workspace = true
