// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
/// Individual search result
#[derive(Clone)]
pub struct SearchResult {
    /// The title of the search result
    pub title: _rt::String,
    /// The URL of the search result
    pub url: _rt::String,
    /// A snippet/description of the search result
    pub description: _rt::String,
}
impl ::core::fmt::Debug for SearchResult {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SearchResult")
            .field("title", &self.title)
            .field("url", &self.url)
            .field("description", &self.description)
            .finish()
    }
}
/// Search response containing structured results
#[derive(Clone)]
pub struct SearchResponse {
    /// List of search results
    pub results: _rt::Vec<SearchResult>,
    /// Query that was executed
    pub query: _rt::String,
}
impl ::core::fmt::Debug for SearchResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SearchResponse")
            .field("results", &self.results)
            .field("query", &self.query)
            .finish()
    }
}
/// Markdown response containing only the search results in markdown format
#[derive(Clone)]
pub struct MarkdownResponse {
    /// Query that was executed
    pub query: _rt::String,
    /// Search results in markdown format
    pub markdown: _rt::String,
}
impl ::core::fmt::Debug for MarkdownResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("MarkdownResponse")
            .field("query", &self.query)
            .field("markdown", &self.markdown)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_search_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::search(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let MarkdownResponse {
                query: query3,
                markdown: markdown3,
            } = e;
            let vec4 = (query3.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len4;
            *ptr2
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr4.cast_mut();
            let vec5 = (markdown3.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr2
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len5;
            *ptr2
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr5.cast_mut();
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr2
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len6;
            *ptr2
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr6.cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_search<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l2 = *arg0
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l4 = *arg0
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
        _ => {
            let l5 = *arg0
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l6 = *arg0
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_search_json_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::search_json(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let SearchResponse {
                results: results3,
                query: query3,
            } = e;
            let vec8 = results3;
            let len8 = vec8.len();
            let layout8 = _rt::alloc::Layout::from_size_align_unchecked(
                vec8.len() * (6 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result8 = if layout8.size() != 0 {
                let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout8);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec8.into_iter().enumerate() {
                let base = result8.add(i * (6 * ::core::mem::size_of::<*const u8>()));
                {
                    let SearchResult {
                        title: title4,
                        url: url4,
                        description: description4,
                    } = e;
                    let vec5 = (title4.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len5;
                    *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (url4.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len6;
                    *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = (description4.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *base
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len7;
                    *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                }
            }
            *ptr2
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len8;
            *ptr2
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = result8;
            let vec9 = (query3.into_bytes()).into_boxed_slice();
            let ptr9 = vec9.as_ptr().cast::<u8>();
            let len9 = vec9.len();
            ::core::mem::forget(vec9);
            *ptr2
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len9;
            *ptr2
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr9.cast_mut();
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec10 = (e.into_bytes()).into_boxed_slice();
            let ptr10 = vec10.as_ptr().cast::<u8>();
            let len10 = vec10.len();
            ::core::mem::forget(vec10);
            *ptr2
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len10;
            *ptr2
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr10.cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_search_json<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l2 = *arg0
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            let base9 = l1;
            let len9 = l2;
            for i in 0..len9 {
                let base = base9.add(i * (6 * ::core::mem::size_of::<*const u8>()));
                {
                    let l3 = *base.add(0).cast::<*mut u8>();
                    let l4 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                    let l5 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l5, l6, 1);
                    let l7 = *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l8 = *base
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l7, l8, 1);
                }
            }
            _rt::cabi_dealloc(
                base9,
                len9 * (6 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let l10 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l11 = *arg0
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l10, l11, 1);
        }
        _ => {
            let l12 = *arg0
                .add(::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l13 = *arg0
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l12, l13, 1);
        }
    }
}
pub trait Guest {
    /// Perform a web search using DuckDuckGo HTML search and return markdown results only
    fn search(query: _rt::String) -> Result<MarkdownResponse, _rt::String>;
    /// Perform a web search using DuckDuckGo HTML search and return structured JSON results
    fn search_json(query: _rt::String) -> Result<SearchResponse, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_duckduckgo_search_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "search")] unsafe extern "C" fn
        export_search(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_search_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_search")] unsafe extern "C" fn _post_return_search(arg0
        : * mut u8,) { unsafe { $($path_to_types)*:: __post_return_search::<$ty > (arg0)
        } } #[unsafe (export_name = "search-json")] unsafe extern "C" fn
        export_search_json(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_search_json_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_search-json")] unsafe extern "C" fn
        _post_return_search_json(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_search_json::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_duckduckgo_search_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea =
    _RetArea([::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()]);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_duckduckgo_search_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_duckduckgo_search_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_duckduckgo_search_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:component:duckduckgo-search:duckduckgo-search:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 388] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfc\x01\x01A\x02\x01\
A\x0d\x01r\x03\x05titles\x03urls\x0bdescriptions\x03\0\x0dsearch-result\x03\0\0\x01\
p\x01\x01r\x02\x07results\x02\x05querys\x03\0\x0fsearch-response\x03\0\x03\x01r\x02\
\x05querys\x08markdowns\x03\0\x11markdown-response\x03\0\x05\x01j\x01\x06\x01s\x01\
@\x01\x05querys\0\x07\x04\0\x06search\x01\x08\x01j\x01\x04\x01s\x01@\x01\x05quer\
ys\0\x09\x04\0\x0bsearch-json\x01\x0a\x04\0-component:duckduckgo-search/duckduck\
go-search\x04\0\x0b\x17\x01\0\x11duckduckgo-search\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
