[package]
name = "fetch-markdown"
version.workspace = true
edition.workspace = true

[package.metadata.component]
package = "component:fetch-markdown"

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
spin-executor.workspace = true
wit-bindgen-rt.workspace = true
