[package]
name = "markdown"
version.workspace = true
edition.workspace = true

[package.metadata.component]
package = "component:markdown"

[lib]
crate-type = ["cdylib"]

[dependencies]
scraper = "0.18"
serde_json.workspace = true
wit-bindgen-rt.workspace = true
