[package]
name = "markdown"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json.workspace = true
scraper = "0.18"
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "component:markdown"
