[package]
name = "fetch"
license = "MIT"
version.workspace = true
edition.workspace = true

[package.metadata.component]
package = "component:fetch"

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
spin-executor = "3.0.1"
wit-bindgen-rt.workspace = true
